spring.application.name=demo

server.port=8080

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

spring.profiles.active=local
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.show-sql=true
spring.mvc.hiddenmethod.filter.enabled=true
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver


file.dir=${user.home}/uploads/
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

spring.datasource.url=jdbc:mariadb://localhost:3306/haeon
spring.datasource.username=ironbear
spring.datasource.password=5959
